version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the frontend application..."
      - npm run build
  post_build:
    commands:
      - echo "Uploading build artifacts to S3..."
      - aws s3 sync build/ s3://frontend-deployment-bucket --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E1KWMKWJVU1UA2 --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: build
cache:
  paths:
    - node_modules/**/*
